/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import FC.DbConnection;
import java.util.ArrayList;
import FC.ConnexionBD;
import FC.Sexe;
import FC.Examen;
import FC.Fonctions;
import FC.Medecin;
import FC.Patient;
import FC.TypeExamen;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Imane
 */
public class Medecin_RechercherPatient extends javax.swing.JFrame {

//    private ArrayList<Patient> lp = new ArrayList<Patient>();
//    private Fonctions f = new Fonctions();
    String IDPatient = "";

    /**
     * Creates new form AccueilSecretaire2
     */
    public Medecin_RechercherPatient() throws SQLException, ParseException {
        initComponents();
        jLabel2.setText("Jean Bono");
        TabInit();

//        DbConnection c = new DbConnection();
//        c.connexionP();
//
//        //on initialise le liste de patients totale à afficher dans le tableau
//        ConnexionBD c1 = new ConnexionBD();
//        c1.connexion();
//        this.lp = c1.recupListeP();
//        DefaultTableModel model = new DefaultTableModel();
//        Object[] title = {"IPP", "IDDMR", "Prenom", "Nom", "DateNaissance", "Sexe"};
//        model.setColumnIdentifiers(title);
//        for (int i = 0; i < lp.size(); i++) {
//            Object[] unPatient = new Object[6];
//            unPatient[0] = lp.get(i).getIPP();
//            unPatient[1] = lp.get(i).getidDMR();
//            unPatient[2] = lp.get(i).getPrenom();
//            unPatient[3] = lp.get(i).getNom();
//            unPatient[4] = lp.get(i).getDateDeNaissance();
//            unPatient[5] = lp.get(i).getSexe();
//
//            model.addRow(unPatient);
//        }
//        tablepatients.setModel(model);
//        tablepatients.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepatients = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        field_nompatient = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        field_prenompatient = new javax.swing.JTextField();
        OK_nompatient = new javax.swing.JButton();
        OK_prenompatient = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rechercher un patient");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(236, 187, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RECHERCHER UN PATIENT");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(jLabel3)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 187, 32), 2));

        tablepatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
<<<<<<< HEAD
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
=======
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
>>>>>>> Interface
            },
            new String [] {
                "idPatient", "idDMR", "Prénom du patient", "Nom du patient", "Sexe", "Date de naissance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablepatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepatientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepatients);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Critères de recherche"));

        jLabel4.setText("Nom du patient : ");

        jLabel5.setText("Prénom du patient :");

        field_prenompatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_prenompatientActionPerformed(evt);
            }
        });

        OK_nompatient.setText("OK");
        OK_nompatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_nompatientActionPerformed(evt);
            }
        });

        OK_prenompatient.setText("OK");
        OK_prenompatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_prenompatientActionPerformed(evt);
            }
        });

        jLabel6.setText("Trier par : ");

        jCheckBox1.setText("Nom");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(field_nompatient, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OK_nompatient))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(field_prenompatient, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OK_prenompatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(jCheckBox1)
                .addGap(391, 391, 391))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(field_nompatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OK_nompatient))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox1))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(field_prenompatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OK_prenompatient))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Connecté(e) en tant que :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton4.setText("Déconnexion");

        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_prenompatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_prenompatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_prenompatientActionPerformed

    private void OK_nompatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_nompatientActionPerformed
        // TODO add your handling code here:
        try {
            DbConnection c = new DbConnection();
            c.connexionP();
            String nom = field_nompatient.getText();
            String query = "SELECT IPP, IDDMR, Prenom, Nom, Sexe, DateNaissance FROM patients WHERE Nom='" + nom + "'";
            ResultSet rs = c.select(query);
            setTable(rs);
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Medecin_AfficherTOUSLESExamens.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OK_nompatientActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void OK_prenompatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_prenompatientActionPerformed
        // TODO add your handling code here:
        try {
            DbConnection c = new DbConnection();
            c.connexionP();
            String prenom = field_prenompatient.getText();
            String query = "SELECT IPP, IDDMR, Prenom, Nom, Sexe, DateNaissance FROM patients WHERE Nom='" + prenom + "'";
            ResultSet rs = c.select(query);
            setTable(rs);
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Medecin_AfficherTOUSLESExamens.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OK_prenompatientActionPerformed

    private void tablepatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepatientsMouseClicked
        // TODO add your handling code here:

        IDPatient = getIDPatient();
        UI.Medecin_AfficherDMR admr;
        try {
            admr = new UI.Medecin_AfficherDMR();
            admr.setVisible(true);
            DbConnection c = new DbConnection();
            c.connexionP();
            String query = "SELECT IPP , pat.Prenom, pat.Nom, DateNaissance, Sexe, Adresse, CodePostal, Ville, pat.IDDMR, DMRPapier FROM `examen` e,`patients` pat WHERE (IPP = '" + IDPatient + "') AND (pat.IDDMR = e.IDDMR)";
            ResultSet rs = c.select(query);
            while (rs.next()) {
                admr.label_adresse.setText(rs.getString("Adresse") + "   " + rs.getString("CodePostal") + "    " + rs.getString("Ville"));
                admr.label_prenomPatient.setText(rs.getString("pat.Prenom"));
                admr.label_nomPatient.setText(rs.getString("pat.Nom"));
                admr.label_datenaissance.setText(rs.getString("DateNaissance").toString());
                admr.label_ipp.setText(rs.getString("IPP"));
                admr.label_sexe.setText(rs.getString("Sexe"));
                admr.label_iddmr.setText(rs.getString("IDDMR"));
                if (rs.getString("DMRPapier").equals("Oui")) {
                    admr.label_dmrpapier.setText("Oui");
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Medecin_AfficherTOUSLESExamens.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tablepatientsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medecin_RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medecin_RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medecin_RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medecin_RechercherPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Medecin_RechercherPatient().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Medecin_RechercherPatient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Medecin_RechercherPatient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK_nompatient;
    private javax.swing.JButton OK_prenompatient;
    private javax.swing.JTextField field_nompatient;
    private javax.swing.JTextField field_prenompatient;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablepatients;
    // End of variables declaration//GEN-END:variables

    public static Sexe stringToSexe(String s) {
        Sexe se = null;
        switch (s) {
            case "Homme":
                se = Sexe.Homme;
                break;
            case "Femme":
                se = Sexe.Femme;
                break;

            default:
                break;

        }
        return se;
    }

    public static TypeExamen stringToTypeExamen(String s) {
        TypeExamen tp = null;
        switch (s) {
            case "SCANNER":
                tp = TypeExamen.SCANNER;
                break;
            case "PET":
                tp = TypeExamen.PET;
                break;
            case "ANGIOGRAPHIE":
                tp = TypeExamen.ANGIOGRAPHIE;
                break;
            case "IRM":
                tp = TypeExamen.IRM;
                break;
            case "RADIOLOGIE":
                tp = TypeExamen.RADIOLOGIE;
                break;
            case "ECHOENDOGRAPHIE":
                tp = TypeExamen.ECHOENDOGRAPHIE;
                break;
            case "RADIOTHRAPIE":
                tp = TypeExamen.RADIOTHERAPIE;
                break;
            case "MAMMOGRAPHIE":
                tp = TypeExamen.MAMMOGRAPHIE;
                break;
            case "ECHOGRAPHIE":
                tp = TypeExamen.ECHOGRAPHIE;
                break;
            default:
                break;

        }
        return tp;
    }

//    public void afficher(String requete) throws ParseException {
//        //this.clearall();
//        ConnexionBD c = new ConnexionBD();
//        c.connexion();
//        ResultSet r = c.exec(requete);
//        ArrayList<Patient> e = new ArrayList<Patient>();
//
//        try {
//            this.lp = f.recupListeP(r);
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Medecin_RechercherPatient.class
//                    .getName()).log(Level.SEVERE, null, ex);
//        }
//
//        c.close();
//    }

//    public void clearall() {
//        for (int i = 0; i < lp.getRowCount(); i++) {
//            for (int j = 0; j < lp.getColumnCount(); j++) {
//                lp.setValueAt("", i, j);
//            }
//        }
//    }
    public void TabInit() throws SQLException {
        DbConnection c = new DbConnection();
        c.connexionP();
        String query = "SELECT IPP, IDDMR, Prenom, Nom, Sexe, DateNaissance FROM patients";
        ResultSet rs = c.select(query);
        setTable(rs);
        c.close();
    }

    public void setTable(ResultSet rs) throws SQLException {
        try {
            while (tablepatients.getRowCount() > 0) {
                ((DefaultTableModel) tablepatients.getModel()).removeRow(0);
            }
            /* On créer un int columns avec le nombre de colonne de notre rs.getMetaData qui prend l'entête*/
            int columns = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                /* On crée un tableau d'objet qui est initialisé avec un nombre de colonne = à columns */
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++) {
                    /* Dans chaque ligne de notre table, on get l'object (donc une ligne de patient) de notre resulset*/
                    row[i - 1] = rs.getObject(i);
                }

                ((DefaultTableModel) tablepatients.getModel()).insertRow(rs.getRow() - 1, row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    public String getIDPatient() {
        String idExamenSelectedRow = tablepatients.getValueAt(tablepatients.getSelectedRow(), 0).toString();
        return idExamenSelectedRow;
    }

}
