/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import FC.DbConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Imane
 */
public class Secretaire_AjouterNouveauPatient extends javax.swing.JFrame {

    /**
     * Creates new form Secretaire_AjouterNouveauPersonnel
     */
    public Secretaire_AjouterNouveauPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        field_nom = new javax.swing.JTextField();
        field_prenom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        field_adresse = new javax.swing.JTextField();
        field_cp = new javax.swing.JTextField();
        field_ville = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bouton_ajouterpatient = new javax.swing.JButton();
        bouton_homme = new javax.swing.JRadioButton();
        bouton_femme = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        field_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(236, 187, 32));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AJOUTER UN NOUVEAU PATIENT AU SERVICE DE RADIOLOGIE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 187, 32), 2));

        jLabel9.setText("Nom :");

        field_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nomActionPerformed(evt);
            }
        });

        field_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_prenomActionPerformed(evt);
            }
        });

        jLabel11.setText("Prénom :");

        jLabel13.setText("Date de Naissance :");

        field_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_cpActionPerformed(evt);
            }
        });

        field_ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_villeActionPerformed(evt);
            }
        });

        jLabel5.setText("Ville :");

        jLabel15.setText("Code postal :");

        jLabel14.setText("Adresse :");

        bouton_ajouterpatient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bouton_ajouterpatient.setText("Ajouter le patient");
        bouton_ajouterpatient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 187, 32), 3));
        bouton_ajouterpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_ajouterpatientActionPerformed(evt);
            }
        });

        bouton_homme.setText("Homme");
        bouton_homme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_hommeActionPerformed(evt);
            }
        });

        bouton_femme.setText("Femme");
        bouton_femme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_femmeActionPerformed(evt);
            }
        });

        jLabel12.setText("Sexe :");

        field_date.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        field_date.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("La date de naissance doit être au format AAAA-MM-JJ   ");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 186, 32), 2), "DMR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel3.setText("Un DMR est automatiquement créé lors de l'admission d'un nouveau patient dans le service de radiologie");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(field_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(bouton_femme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bouton_homme))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bouton_ajouterpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(field_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(field_ville))
                            .addComponent(field_adresse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(field_date)
                                    .addComponent(field_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(field_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouton_femme)
                    .addComponent(bouton_homme)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(field_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(field_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(field_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(field_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(field_ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(bouton_ajouterpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nomActionPerformed

    private void field_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_prenomActionPerformed

    private void field_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_cpActionPerformed

    private void field_villeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_villeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_villeActionPerformed

    private void bouton_ajouterpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_ajouterpatientActionPerformed
        // TODO add your handling code here:
        boolean reponse = true;
        int IPP = 0;
        int IDDMR = 0;
        DbConnection c = new DbConnection();
        c.connexionB();

        //Vérification que tous les champs sont remplis
        if (field_date.getText().equals("") | field_nom.getText().equals("") | field_prenom.getText().equals("") | field_adresse.getText().equals("") | field_cp.getText().equals("")
                | field_ville.getText().equals("") | (bouton_femme.isSelected() == false && bouton_homme.isSelected() == false)) {
            JOptionPane.showMessageDialog(null, "Des informations sont manquantes, veuillez vérifier que tous les champs ont bien été renseignés.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else {

            //Vérification du format de la date
            if (field_date.getText().matches("[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])")) {

                //Vérification que le patient n'existe pas déjà
                String requete_test = "SELECT * FROM patients WHERE Nom = '" + field_nom.getText() + "' AND Prenom = '" + field_prenom.getText() + "'";
                ResultSet verif_patient_existe = c.select(requete_test);

                try {
                    if (verif_patient_existe.next()) {

                        int i = JOptionPane.showConfirmDialog(this, "Il existe déjà un patient avec ce nom et prénom (" + field_prenom.getText() + "  " + field_nom.getText() + ")\n Souhaitez-vous toujours admettre ce patient ? ",
                                "Information", JOptionPane.YES_NO_OPTION);

                        if (i == JOptionPane.YES_OPTION) {
                            reponse = true;
                        } else {
                            reponse = false;
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Secretaire_AjouterNouveauPatient.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (reponse) {
                    String max_ipp = "SELECT * from patients where IPP = (SELECT MAX(IPP) from patients)";
                    String max_dmr = "SELECT * from patients where IDDMR = (SELECT MAX(IDDMR) from patients)";
                    ResultSet bd_max_ipp = c.select(max_ipp);
                    try {
                        while (bd_max_ipp.next()) {
                            IPP = Integer.parseInt(bd_max_ipp.getString("IPP")) + 1; //Transforme le champ IPP (varchar) en Int et ajoute 1
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(Secretaire_AjouterNouveauPatient.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    ResultSet bd_max_iddmr = c.select(max_dmr);
                    try {
                        while (bd_max_iddmr.next()) {
                            IDDMR = Integer.parseInt(bd_max_iddmr.getString("IDDMR")) + 1; //Transforme le champ IDDMR (varchar) en Int et ajoute 1
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(Secretaire_AjouterNouveauPatient.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    //Si le patient est un homme
                    if (bouton_homme.isSelected()) {
                        String s = "INSERT INTO patients (`IPP`,`Nom`, `Prenom`, `Sexe`, `DateNaissance`,`Adresse`,`CodePostal`,`Ville`,`IDDMR`) VALUES ('" + IPP + "','" + field_nom.getText() + "','" + field_prenom.getText() + "','" + "Homme"
                                + "','" + field_date.getText() + "','" + field_adresse.getText() + "', '" + field_cp.getText() + "','" + field_ville.getText() + "', '" + IDDMR + "')";
                        try {
                            c.update(s);
                        } catch (SQLException ex) {
                            Logger.getLogger(Secretaire_AjouterNouveauPatient.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        //Si le patient est une femme
                        if (bouton_femme.isSelected()) {
                            String p = "INSERT INTO patients (`IPP`,`Nom`, `Prenom`, `Sexe`, `DateNaissance`,`Adresse`,`CodePostal`,`Ville`,`IDDMR`) VALUES ('" + IPP + "','" + field_nom.getText() + "','" + field_prenom.getText() + "','" + "Femme"
                                    + "','" + field_date.getText() + "','" + field_adresse.getText() + "', '" + field_cp.getText() + "','" + field_ville.getText() + "', '" + IDDMR + "' )";
                            try {
                                c.update(p);
                            } catch (SQLException ex) {
                                Logger.getLogger(Secretaire_AjouterNouveauPatient.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }

                    }
                    JOptionPane.showMessageDialog(null, "Le patient a bien été ajouté à la base de données.", "Information", JOptionPane.INFORMATION_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(null, "Le format de la date est erroné, veuillez la renseigner à nouveau.", "Attention", JOptionPane.INFORMATION_MESSAGE);
            }

            dispose();
        }
    }//GEN-LAST:event_bouton_ajouterpatientActionPerformed

    private void bouton_hommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_hommeActionPerformed

    }//GEN-LAST:event_bouton_hommeActionPerformed

    private void bouton_femmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_femmeActionPerformed

    }//GEN-LAST:event_bouton_femmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secretaire_AjouterNouveauPatient.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secretaire_AjouterNouveauPatient.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secretaire_AjouterNouveauPatient.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secretaire_AjouterNouveauPatient.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secretaire_AjouterNouveauPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_ajouterpatient;
    private javax.swing.JRadioButton bouton_femme;
    private javax.swing.JRadioButton bouton_homme;
    private javax.swing.JTextField field_adresse;
    private javax.swing.JTextField field_cp;
    private javax.swing.JTextField field_date;
    private javax.swing.JTextField field_nom;
    private javax.swing.JTextField field_prenom;
    private javax.swing.JTextField field_ville;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
